### PR TITLE
Remove moq

### PR DESCRIPTION
**Pull request by rasmus**
Permanently remove moq after https://github.com/moq/moq/issues/1374

### CODE REVIEW

**Comment by tonyqus** [comment]
I got to know eventflow due to https://github.com/moq/moq/issues/1374. Perhaps you should reconsider it.

**Comment by rasmus** [comment]
Thanks @tonyqus, already started a PR https://github.com/eventflow/EventFlow/pull/1001 😄

**Comment by rasmus** [comment]
Or do you think I should reconsider removing moq? Just saw that I might have misunderstood your comment

**Comment by rasmus** [comment]
> To be clear, this new behavior is deeply problematic (for multiple reasons) and unacceptable for a dependency of ours.
`https://github.com/dotnet/runtime/issues/90222#issuecomment-1671834283`

**Comment by tonyqus** [comment]
There is not much usage of Moq in your project. That's the major reason you can easily remove it. However, most companies are heavily using Moq. It's hard to remove it because it may costs a few days or even a month to rewrite the code.

**Comment by rasmus** [comment]
We also use Moq at work, heck I even think I was part of introducing it, but as mentioned by one of the maintainers of StackExchange.Redis here https://github.com/moq/moq/issues/1374#issuecomment-1671166436, there are other good alternatives and even the chance of having to deal with privacy issues is not worth having it. After having read the entire thread and follow what `@kzu` writes in response in the issues, its clear that his views on privacy, OSS and general "good practices" doesn't align with mine. I'm the author of https://github.com/eventflow/EventFlow (and its hard to buy even a cup of coffee for the sponsorship/donations I have received there) and removing Moq is going to take a lot of work, work that I really, really don't need right now, but I think its important for everyone to move away from this as this asap. What the author has done, and still seems to really want to do, is doing really hurt the open source community and I don't want to support that.

**Pull request merged**
